name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2' # Specify a Ruby version compatible with Jekyll
        bundler-cache: true # Cache dependencies for faster builds

    - name: Install dependencies
      run: bundle install

    - name: Build the site
      run: bundle exec jekyll build --future

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main' # Only deploy on push to main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site